version: '2'
services:
  php5:
    image: otctf/default:php5
    container_name: php5
    command: bash
    tty: true
    security_opt:
      - seccomp=unconfined  # make debug server working
    volumes:
      - ./qs:/home/qs
